name: Upload Python Package to PyPI when a Release is Created

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/httomo-backends
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel          
          $CONDA/bin/conda install conda-forge::tomopy
          $CONDA/bin/conda install httomo::httomolib
          $CONDA/bin/conda install conda-forge::pyyaml
          $CONDA/bin/conda list
      - name: Generate yaml templates
        run: |
          $CONDA/bin/python ./httomo_backends/scripts/yaml_templates_generator.py -i ./httomo_backends/methods_database/backends/tomopy/tomopy_modules.yaml -o ./httomo_backends/yaml_templates/tomopy
          $CONDA/bin/python ./httomo_backends/scripts/yaml_unsupported_tomopy_remove.py -t ./httomo_backends/yaml_templates/tomopy -l ./httomo_backends/methods_database/backends/tomopy/tomopy.yaml
          $CONDA/bin/python ./httomo_backends/scripts/yaml_templates_generator.py -i ./httomo_backends/methods_database/backends/httomolib/httomolib_modules.yaml -o ./httomo_backends/yaml_templates/httomolib
      - name: Build package
        run: |
          python -m pip install build   
          python -m build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1